/**
 * Writes the published PDFs' sizes into a generated module. The sizes cannot
 * be read at runtime: on Workers a static asset is not fetchable from inside
 * the worker, which silently produced "0 kB" download labels.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = 'static/documents';
const sizes = Object.fromEntries(
	readdirSync(dir)
		.filter((f) => f.endsWith('.pdf'))
		.map((f) => [`/documents/${f}`, statSync(join(dir, f)).size])
);

const kit = 'static/brand/mementomori-ry-brand-kit.zip';
const kitSize = statSync(kit).size;

writeFileSync(
	'src/lib/document-sizes.ts',
	`// Generated by scripts/doc-sizes.mjs. Do not edit.\nexport const DOCUMENT_SIZES: Record<string, number> = ${JSON.stringify(sizes, null, '\t')};\nexport const BRAND_KIT_SIZE = ${kitSize};\n`
);
console.log(
	`doc-sizes: ${Object.keys(sizes).length} documents, brand kit ${(kitSize / 1024 / 1024).toFixed(1)} MB`
);
